var CowInfo = [];
/*"normal" cows start*/
// any cow whith a picture named "mk2_cow[number].png" is from when i was calling all of the different cow images by changing the image name directly
// the current method is designed to be human readable which allows for actually seeing problems and better reordering of the cows if needed
//Cow #1
CowInfo.push({	Name:'Brown Swiss', 		
				Rarity:"Rarity_Poor", 		
				Cow_image: 'sprite_Brown_swiss_cow.png', 		
				Bull_image: 'mk2_bull0.png', 					
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'mk2_cow0.png', 
				Achievment_image_Xbull:'mk2_bull0.png'});
//Cow #2
CowInfo.push({	Name:'Norwegian Red', 		
				Rarity:"Rarity_Poor", 		
				Cow_image: 'sprite_Norwegian_red_cow.png', 	
				Bull_image: 'mk2_bull1.png', 				
				Bull_Name: 'Bull',		
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'mk2_cow1.png',
				Achievment_image_Xbull:'mk2_bull0.png'});
//Cow #3
CowInfo.push({	Name:'English Longhorn', 	
				Rarity:"Rarity_Poor", 	
				Cow_image: 'sprite_English Longhorn_cow.png', 	
				Bull_image: 'mk2_bull2.png', 					
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'mk2_cow2.png',
				Achievment_image_Xbull:'mk2_bull2.png'});
//Cow #4
CowInfo.push({	Name:'Aberdeen Angus', 		
				Rarity:"Rarity_Poor", 	
				Cow_image: 'sprite_Aberdeen Angus_cow.png', 	
				Bull_image: 'mk2_bull3.png', 					
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'mk2_cow3.png',
				Achievment_image_Xbull:'mk2_bull3.png'});
//Cow #5
CowInfo.push({	Name:'Holstein Friesian', 
				Rarity:"Rarity_Poor", 	
				Cow_image: 'sprite_Holstein Friesian_cow.png', 	
				Bull_image: 'mk2_bull4.png', 					
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'mk2_cow4.png',
				Achievment_image_Xbull:'mk2_bull4.png'});
//Cow #6
CowInfo.push({	Name:'Belgian Blue',		
				Rarity:"Rarity_Poor", 		
				Cow_image: 'sprite_Belgian Blue_cow.png', 		
				Bull_image: 'belgian_blue_bull.png', 			
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'belgian_blue_cow.png',
				Achievment_image_Xbull:'belgian_blue_bull.png'});
//Cow #7
CowInfo.push({	Name:'Hereford',			
				Rarity:"Rarity_Poor", 		
				Cow_image: 'sprite_Hereford_cow.png', 			
				Bull_image: 'Hereford_bull.png', 				
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'Hereford_cow.png',
				Achievment_image_Xbull:'Hereford_bull.png'});
//Cow #8
CowInfo.push({	Name:'Glocester',			
				Rarity:"Rarity_Poor", 		
				Cow_image: 'sprite_Glocester_cow.png', 			
				Bull_image: 'glocester_bull.png', 				
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'glocester_cow.png',
				Achievment_image_Xbull:'glocester_bull.png'});
//Cow #9
CowInfo.push({	Name:'Semmental',			
				Rarity:"Rarity_Poor", 		
				Cow_image: 'sprite_Semmental_cow.png', 			
				Bull_image: 'semmental_bull.png', 				
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'semmental_cow.png',
				Achievment_image_Xbull:'semmental_bull.png'});
//Cow #10
CowInfo.push({	Name:'Irish Moiled',		
				Rarity:"Rarity_Poor", 		
				Cow_image: 'sprite_Irish Moiled_cow.png', 		
				Bull_image: 'irish_moiled_bull.png', 			
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'irish_moiled_cow.png',
				Achievment_image_Xbull:'irish_moiled_bull.png'});
//Cow #11
CowInfo.push({	Name:'Belted Galloway', 	
				Rarity:"Rarity_Poor", 		
				Cow_image: 'sprite_Belted Galloway_cow.png', 	
				Bull_image: 'mk2_bull6.png', 					
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'mk2_cow6.png',
				Achievment_image_Xbull:'mk2_bull6.png'});
//Cow #12
CowInfo.push({	Name:'Charolais', 			
				Rarity:"Rarity_Poor", 		
				Cow_image: 'sprite_Charolais_cow.png', 			
				Bull_image: 'mk2_bull5.png', 					
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'mk2_cow5.png',
				Achievment_image_Xbull:'mk2_bull5.png'});
//Cow #13
CowInfo.push({	Name:'Speckle Park',		
				Rarity:"Rarity_Poor", 		
				Cow_image: 'sprite_Speckle Park_cow.png', 		
				Bull_image: 'speckle_park_bull.png', 			
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'speckle_park_cow.png',
				Achievment_image_Xbull:'speckle_park_bull.png'});
//Cow #14
CowInfo.push({	Name:'Texas Longhorn',		
				Rarity:"Rarity_Poor", 		
				Cow_image: 'sprite_Texas Longhorn_cow.png', 	
				Bull_image: 'Texas_longhorn_bull.png', 			
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'Texas_longhorn_cow.png',
				Achievment_image_Xbull:'Texas_longhorn_bull.png'});
//Cow #15
CowInfo.push({	Name:'Ankole-Watusi',		
				Rarity:"Rarity_Poor", 		
				Cow_image: 'sprite_Ankole-Watusi_cow.png', 		
				Bull_image: 'ankole-watusi_bull.png', 			
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'ankole-watusi_cow.png',
				Achievment_image_Xbull:'ankole-watusi_bull.png'});
//Cow #16
CowInfo.push({	Name:'White Park',			
				Rarity:"Rarity_Poor", 		
				Cow_image: 'sprite_White Park_cow.png', 		
				Bull_image: 'white_park_bull.png', 				
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'white_park_cow.png',
				Achievment_image_Xbull:'white_park_bull.png'});
//Cow #17
CowInfo.push({	Name:'Scottish Highland', 
				Rarity:"Rarity_Poor", 		
				Cow_image: 'sprite_Scottish Highland_cow.png', 	
				Bull_image: 'mk2_bull7.png', 					
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'mk2_cow7.png',
				Achievment_image_Xbull:'mk2_bull7.png'});
//Cow #18
CowInfo.push({	Name:'Lakenvelder',			
				Rarity:"Rarity_Poor", 		
				Cow_image: 'sprite_Lakenvelder_cow.png', 		
				Bull_image: 'lakenvelder_bull.png', 			
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'lakenvelder_cow.png',
				Achievment_image_Xbull:'lakenvelder_bull.png'});
/*"normal cows" end weird cows start*/
//Cow #19
CowInfo.push({	Name:'Australian Longhorn', 	
				Rarity:"Rarity_Common", 	
				Cow_image: 'sprite_Australian_Longhorn_cow.png',
				Bull_image: 'mk2_bull10.png', 					
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'mk2_cow10.png',
				Achievment_image_Xbull:'mk2_bull10.png'});
//Cow #20
CowInfo.push({	Name:'Mammuthus primigenius',	
				Rarity:"Rarity_Common", 	
				Cow_image: 'sprite_Mammuth_cow.png', 			
				Bull_image: 'mk2_bull9.png', 					
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'mk2_cow9.png',
				Achievment_image_Xbull:'mk2_bull9.png'});
//Cow #21
CowInfo.push({	Name:'Cowabunga', 			
				Rarity:"Rarity_Common", 	
				Cow_image: 'sprite_Cowabunga_cow.png', 			
				Bull_image: 'mk2_bull11.png', 					
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'mk2_cow11.png',
				Achievment_image_Xbull:'mk2_bull11.png'});
//Cow #22
CowInfo.push({	Name:'Bit-Cow', 				
				Rarity:"Rarity_Common", 	
				Cow_image: 'bit_cow.png', 						
				Bull_image: 'bit_bull.png', 					
				Bull_Name: 'Bull',			
				Is_Sprite: 'NO', 
				Achievment_image_Xcow: 'bit_cow.png',
				Achievment_image_Xbull:'bit_bull.png'});
//Cow #23
CowInfo.push({	Name:'Moostache', 			
				Rarity:"Rarity_Common", 	
				Cow_image: 'sprite_Moostache_cow.png', 			
				Bull_image: 'moostache_bull.png', 				
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'moostache_cow.png',
				Achievment_image_Xbull:'moostache_bull.png'});
//Cow #24
CowInfo.push({	Name:'Lacertilia Bos Taurus',	
				Rarity:"Rarity_Common", 	
				Cow_image: 'sprite_lizard_cow.png', 			
				Bull_image: 'mk2_bull8.png', 					
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'mk2_cow8.png',
				Achievment_image_Xbull:'mk2_bull8.png'});
//Cow #25
CowInfo.push({	Name:'See-Cow', 			
				Rarity:"Rarity_Common", 	
				Cow_image: 'sprite_See-Cow_cow.png', 			
				Bull_image: 'mk2_bull12.png', 					
				Bull_Name: 'See-Bull',		
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'mk2_cow12.png',
				Achievment_image_Xbull:'mk2_bull12.png'});
//Cow #26
CowInfo.push({	Name:'Mootant', 				
				Rarity:"Rarity_Common", 	
				Cow_image: 'Mutant_cow.png', 					
				Bull_image: 'Mutant_bull.png', 					
				Bull_Name: 'Bull',			
				Is_Sprite: 'NO', 
				Achievment_image_Xcow: 'Mutant_cow.png',
				Achievment_image_Xbull:'Mutant_bull.png'});
//Cow #27
CowInfo.push({	Name:'Sea-Cow', 				
				Rarity:"Rarity_Common", 	
				Cow_image: 'mk2_cow15.png', 					
				Bull_image: 'mk2_bull15.png', 					
				Bull_Name: 'Sea-Bull',		
				Is_Sprite: 'NO', 
				Achievment_image_Xcow: 'mk2_cow15.png',
				Achievment_image_Xbull:'mk2_bull15.png'});
//Cow #28
CowInfo.push({	Name:'Byte-Cow', 				
				Rarity:"Rarity_Common", 	
				Cow_image: 'byte_cow.png', 						
				Bull_image: 'byte_bull.png', 					
				Bull_Name: 'Bull',			
				Is_Sprite: 'NO', 
				Achievment_image_Xcow: 'byte_cow.png',
				Achievment_image_Xbull:'byte_bull.png'});
//Cow #29
CowInfo.push({	Name:'Moose Cow',				
				Rarity:"Rarity_Common", 	
				Cow_image: 'sprite_Moose_cow.png', 				
				Bull_image: 'Moose-Bull.png', 					
				Bull_Name: 'Moose Bull',	
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'Moose-cow.png',
				Achievment_image_Xbull:'Moose-Bull.png'});
//Cow #30
CowInfo.push({	Name:'Red Cower-Ranger', 	
				Rarity:"Rarity_Uncommon", 
				Cow_image: 'sprite_Red Cower-Ranger_cow.png', 	
				Bull_image: 'red_cower_ranger_bull.png', 		
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'red_cower_ranger_cow.png',
				Achievment_image_Xbull:'red_cower_ranger_bull.png'});
//Cow #31
CowInfo.push({	Name:'Blue Cower-Ranger', 
				Rarity:"Rarity_Uncommon", 	
				Cow_image: 'sprite_Blue Cower-Ranger_cow.png', 	
				Bull_image: 'blue_cower_ranger_bull.png', 		
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'blue_cower_ranger_cow.png',
				Achievment_image_Xbull:'blue_cower_ranger_bull.png'});
//Cow #32
CowInfo.push({	Name:'Pink Cower-Ranger', 
				Rarity:"Rarity_Uncommon", 	
				Cow_image: 'sprite_Pink Cower-Ranger_cow.png', 	
				Bull_image: 'pink_cower_ranger_bull.png', 		
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'pink_cower_ranger_cow.png',
				Achievment_image_Xbull:'pink_cower_ranger_bull.png'});
//Cow #33
CowInfo.push({	Name:'Yellow Cower-Ranger', 	
				Rarity:"Rarity_Uncommon", 	
				Cow_image: 'sprite_Yellow Cower-Ranger_cow.png',
				Bull_image: 'yellow_cower_ranger_bull.png', 	
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'yellow_cower_ranger_cow.png',
				Achievment_image_Xbull:'yellow_cower_ranger_bull.png'});
//Cow #34
CowInfo.push({	Name:'Black Cower-Ranger', 	
				Rarity:"Rarity_Uncommon", 	
				Cow_image: 'sprite_Black Cower-Ranger_cow.png', 
				Bull_image: 'black_cower_ranger_bull.png', 		
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'black_cower_ranger_cow.png',
				Achievment_image_Xbull:'black_cower_ranger_bull.png'});
//Cow #35
CowInfo.push({	Name:'Bite-Cow', 				
				Rarity:"Rarity_Uncommon", 	
				Cow_image: 'sprite_Bite_cow.png', 			
				Bull_image: 'bite_bull.png', 				
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'bite_cow.png',
				Achievment_image_Xbull:'bite_bull.png'});
//Cow #36
CowInfo.push({	Name:'Unihorn', 				
				Rarity:"Rarity_Uncommon", 	
				Cow_image: 'mk2_cow16.png', 					
				Bull_image: 'mk2_bull16.png', 				
				Bull_Name: 'Bull',		
				Is_Sprite: 'NO', 
				Achievment_image_Xcow: 'mk2_cow16.png',
				Achievment_image_Xbull:'mk2_bull16.png'});
//Cow #37
CowInfo.push({	Name:'Peregrine Cow',		
				Rarity:"Rarity_Uncommon", 	
				Cow_image: 'sprite_Peregrine_cow.png', 			
				Bull_image: 'Falcon_bull.png', 				
				Bull_Name: 'Bull',		
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'Falcon_cow.png',
				Achievment_image_Xbull:'Falcon_bull.png'});
//Cow #38
CowInfo.push({	Name:'Long Cow',				
				Rarity:"Rarity_Uncommon",	
				Cow_image: 'snek_female.png',					
				Bull_image: 'snek_male.png', 				
				Bull_Name: 'Long Bull',	
				Is_Sprite: 'NO', 
				Achievment_image_Xcow: 'snek_female.png',
				Achievment_image_Xbull:'snek_male.png'});
//Cow #39
CowInfo.push({	Name:'Cowdozer',				
				Rarity:"Rarity_Uncommon",	
				Cow_image: 'bulldozer.png',						
				Bull_image: 'bulldozer.png', 					
				Bull_Name: 'Bulldozer',		
				Is_Sprite: 'NO', 
				Achievment_image_Xcow: 'bulldozer.png',
				Achievment_image_Xbull:'bulldozer.png'});
//Cow #40
CowInfo.push({	Name:'White Cower-Ranger', 
				Rarity:"Rarity_Rare", 		
				Cow_image: 'sprite_White Cower-Ranger.png', 	
				Bull_image: 'white_cower_ranger_bull.png', 		
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'white_cower_ranger_cow.png',
				Achievment_image_Xbull:'white_cower_ranger_bull.png'});
//Cow #41
CowInfo.push({	Name:'Light-Cow', 			
				Rarity:"Rarity_Rare", 		
				Cow_image: 'mk2_cow18.png', 					
				Bull_image: 'mk2_bull18.png', 					
				Bull_Name: 'Light-Bull',	
				Is_Sprite: 'NO', 
				Achievment_image_Xcow: 'mk2_cow18.png',
				Achievment_image_Xbull:'mk2_bull18.png'});
//Cow #42
CowInfo.push({	Name:'Dark-Cow', 				
				Rarity:"Rarity_Rare", 		
				Cow_image: 'mk2_cow17.png', 					
				Bull_image: 'mk2_bull17.png', 					
				Bull_Name: 'Dark-Bull',		
				Is_Sprite: 'NO', 
				Achievment_image_Xcow: 'mk2_cow17.png',
				Achievment_image_Xbull:'mk2_bull17.png'});
//Cow #43
CowInfo.push({	Name:'Glacial-Cow', 			
				Rarity:"Rarity_Rare", 		
				Cow_image: 'sprite_Glacial_cow.png', 			
				Bull_image: 'mk2_bull13.png', 					
				Bull_Name: 'Glacial-Bull',	
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'mk2_cow13.png',
				Achievment_image_Xbull:'mk2_bull13.png'});
//Cow #44
CowInfo.push({	Name:'Volcanic-Cow', 			
				Rarity:"Rarity_Rare", 		
				Cow_image: 'mk2_cow14.png', 					
				Bull_image: 'mk2_bull14.png', 					
				Bull_Name: 'Volcanic-Bull',	
				Is_Sprite: 'NO', 
				Achievment_image_Xcow: 'mk2_cow14.png',
				Achievment_image_Xbull:'Volcanic-Bull'});
//Cow #45
CowInfo.push({	Name:'Trojan-Cow',			
				Rarity:"Rarity_Epic", 		
				Cow_image: 'sprite_Trojan_cow.png', 			
				Bull_image: 'Trojan_bull.png', 					
				Bull_Name: 'Trojan-Bull',	
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'Trojan_cow.png',
				Achievment_image_Xbull:'Trojan_bull.png'});
//Cow #46
CowInfo.push({	Name:'Sobek', 				
				Rarity:"Rarity_Legendary", 	
				Cow_image: 'sprite_Sobek_cow.png', 				
				Bull_image: 'sobek_bull.png', 					
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'sobek_cow.png',
				Achievment_image_Xbull:'sobek_bull.png'});
//Cow #47
CowInfo.push({	Name:'Ra', 					
				Rarity:"Rarity_Legendary", 	
				Cow_image: 'sprite_Ra_cow.png', 				
				Bull_image: 'Ra_bull.png', 						
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'Ra_cow_mk2.png',
				Achievment_image_Xbull:'Ra_bull.png'});
//Cow #48
CowInfo.push({	Name:'Hathor', 				
				Rarity:"Rarity_Legendary", 	
				Cow_image: 'sprite_Hathor_cow.png', 			
				Bull_image: 'hathor_bull.png', 					
				Bull_Name: 'Bull',			
				Is_Sprite: 'YES', 
				Achievment_image_Xcow: 'hathor_cow.png',
				Achievment_image_Xbull:'hathor_bull.png'});
/*cows end*/

// --------- Other Cow Ideas -------------
// SarCowphagus - sarcophogus themed cow
// Accowntant
// Cownt Dracular
// Cattlefish
// Bullfrog - just a frog
// Cower Rangers - a load of different colours, maybe a combined "zord" cow as well
// 					- power ranger main set is Black/Blue/Yellow/Pink/Red with special power rangers being Green/white
//					- the origonal Megazord was a combination of Red/Black/Blue/Yellow/pink
// Cowtron - voltron cow Black/Red/Green/Yellow/Blue cows combine into 1 voltron cow
// Done ------> Moose - just a moose
// Cowzilla - godzilla cow
// Moothra - Mothra Cow
// Moouse - a mouse cow, maybe just a mouse
// Close encownters - alien or space ship cow
// Mootians - Martian cow
// Cowculator - calculator cow
// Moosician - some sort of musical cow
// Moodus - Midus cow, like just a gold cow or something
// Done ------> Mootant - Mutant cow
// Moovie cow - not sure but goes with the matrix cows
// Matrix cow - both a Matrix the film and Matrix the maths thing
// Moozarella - cheese cow
// Cowcium - Calcium cow
// Skeleton cow
// cash cow
// long cow 2 - giraffe, maybe loonge cow maybe change the snake to like slithery cow or something
// 		- giraffe
//		- black and white giraffe "Holstein Friesian" long cow or something

// Gem cows - Saphire/emerald/ruby/diamond/ect.
// Other Egyption Gods
//		- Anubis - Jackal
//		- Apis - Bull
// 		- Apophis - Snake
//		- Bastet - Cat
// 		- Horus - Falcon ---- 	not sure how to differentiate between Horus and Ra, though the "eye of Horus" is probably the way to go
//								Horus is the Sky god where Ra is a Sun god, possible use that?
// 		- Khepri - Scarab
// 		- Sekhmet - Lioness
//		- Thoth - Sacred Ibis (a kinda crane thing)
//		- Amun - Ram
//		Done ------> Sobek - Crocodile
//		Done ------> Ra - Falcon
//		Done ------> Hathor - Cow

// ------------ Non Cow Ideas ---------
// -- Add back removed features --
//		- missing tooltips
//			- COWS
//			- train specialists
//			- milkmaid buy 10/100/max
//			- MIlk (not sure if this ever had one)

// --- fix the refresh issues ---

//	-- new/different game mechanics --
//		-- prestige --
//			- IE. at some point in the game you restart and get a boost.
//		-- change how cows are unlocked --
//			- science maybe
//		-- tech tree?
//

//	-- Single button for buy 1/10/100/1000 etc
// 		To remove clutter, having a button that changes all of the buy options between the Buy 
//		1/10/100/1000 options, it should also allow the player to buy however many of the thing 
// 		that they can afford. 
//		so if they have the buy 100 option selected but can only afford 50 they still buy 50.

//	-- Milkmaid priority buy specialists
// 		It is pretty easy to get to a point where milkmaids are more powerfull than some of the specialists,
//		so having an option to keep a number of cows without specialists would meen you dont have to wait the 
//		10s for more cows to spawn. 

// -- Upgrades --
// 		- More upgrades for specialists
//		- different types of grass for cows
// 		- feed upgrades?

// -- Achievements
//		Done ------> - unlock each cow
//		Done ------> - X of each cow (10/100/1000/etc) [not sure what the best numbers are]
//		- X of specialists
//		- X of Milkmaids
//		- X MILK
//		- X Spec level
//		- X clicks (I am recording how many clicks on the milk button)
// 		- X MPS
//		- Achievments unlock something
//			- bonus milk (multiply the milk from that cow for the chieve maybe?)
//		- Achievment art
//			- for not cows/bulls/specialists i will need to make new art

// -- story line --
//		- identical intro to jack and the bean stalk
//		- but rather than magic beans the weird dude talks about just making milk into more cows

// ------ Actual jack and the bean stalk intro ------
// There was once upon a time a poor widow who had an only son named Jack, and a cow named Milky-White. 
// All they had to live on was the milk the cow gave every morning, which they carried to the market and sold - until one morning Milky-White gave no milk.
// “What shall we do, what shall we do?” said the widow, wringing her hands.
// “Cheer up mother, I’ll go and get work somewhere,” said Jack.
// “We’ve tried that before, and nobody would take you,” said his mother. “We must sell Milky-White and with the money, start a shop or something.”
// “Alright, mother,” said Jack. “It’s market day today, and I’ll soon sell Milky-White, and then we’ll see what we can do.”
// So he took the cow, and off he started. He hadn’t gone far when he met a funny looking old man, who said to him, “Good morning, Jack.”
// “Good morning to you,” said Jack, and wondered how he knew his name.
// “Well Jack, where are you off to?” Said the man.
// “I’m going to market to sell our cow there.”
// “Oh, you look the proper sort of chap to sell cows,” said the man. “I wonder if you know how many beans make five.”
// “Two in each hand and one in your mouth,” said Jack, as sharp as a needle.
// “Right you are,” says the man, “and here they are, the very beans themselves,” he went on, pulling out of his pocket a number of strange looking beans. 
// “As you are so sharp,” said he, “I don’t mind doing a swap with you — your cow for these beans.”
// “Go along,” said Jack. “You take me for a fool!”
// “Ah! You don’t know what these beans are,” said the man. “If you plant them overnight, by morning they grow right up to the sky.”
// “Really?” said Jack. “You don’t say so.”
// “Yes, that is so. If it doesn’t turn out to be true you can have your cow back.”
// “Right,” said Jack, and handed him over Milky-White, then pocketed the beans.

// -- dumb version for game
// Once upon a time a poor farmer was walking into town with a cow they planned on selling
// a mysterious stranger beconed to the farmer from a allyway
// "where are you taking that cow" - says the stranger
// "If I sell this cow at the market I can afford this months rent" says the farmer
// "why dont you milk the cow" - stranger
// "A few liters of milk isnt going to get me enough money" - farmer
// "well what if you use that milk to buy more cows" - stranger
// "I am pretty sure you dont know how dairy farming works" - farmer
// "how long have you got till rent is due? why not try it and if it doesnt work you can sell your cow before then" - stranger
// "Look mate, I have a whole dairy farm, 1 cow isnt going to change how much milk i can produce by very much" - farmer
// "alright then how about a bet, I take this cow for a little bit and if my plan works I keep the cow and if it doesnt I will pay double what this cow is worth" - stranger
// "ok fine, but you better have that money ready." - farmer
// ------- for some reason we are the stranger now lol ------




var NumberofCOWS = CowInfo.length - 1; 

function Names(){
	var Randomnumber_gender = Math.random();
	var Randomnumber_Name = Math.floor(Math.random()*1000);
	if(Randomnumber_gender > 0.5){
		return Girls_names[Randomnumber_Name];
	}
	else{
		return Boys_names[Randomnumber_Name];
	};
};

var Girls_names = [	"Olivia",
"Emma",
"Ava",
"Charlotte",
"Sophia",
"Amelia",
"Isabella",
"Mia",
"Evelyn",
"Harper",
"Camila",
"Gianna",
"Abigail",
"Luna",
"Ella",
"Elizabeth",
"Sofia",
"Emily",
"Avery",
"Mila",
"Scarlett",
"Eleanor",
"Madison",
"Layla",
"Penelope",
"Aria",
"Chloe",
"Grace",
"Ellie",
"Nora",
"Hazel",
"Zoey",
"Riley",
"Victoria",
"Lily",
"Aurora",
"Violet",
"Nova",
"Hannah",
"Emilia",
"Zoe",
"Stella",
"Everly",
"Isla",
"Leah",
"Lillian",
"Addison",
"Willow",
"Lucy",
"Paisley",
"Natalie",
"Naomi",
"Eliana",
"Brooklyn",
"Elena",
"Aubrey",
"Claire",
"Ivy",
"Kinsley",
"Audrey",
"Maya",
"Genesis",
"Skylar",
"Bella",
"Aaliyah",
"Madelyn",
"Savannah",
"Anna",
"Delilah",
"Serenity",
"Caroline",
"Kennedy",
"Valentina",
"Ruby",
"Sophie",
"Alice",
"Gabriella",
"Sadie",
"Ariana",
"Allison",
"Hailey",
"Autumn",
"Nevaeh",
"Natalia",
"Quinn",
"Josephine",
"Sarah",
"Cora",
"Emery",
"Samantha",
"Piper",
"Leilani",
"Eva",
"Everleigh",
"Madeline",
"Lydia",
"Jade",
"Peyton",
"Brielle",
"Adeline",
"Vivian",
"Rylee",
"Clara",
"Raelynn",
"Melanie",
"Melody",
"Julia",
"Athena",
"Maria",
"Liliana",
"Hadley",
"Arya",
"Rose",
"Reagan",
"Eliza",
"Adalynn",
"Kaylee",
"Lyla",
"Mackenzie",
"Alaia",
"Isabelle",
"Charlie",
"Arianna",
"Mary",
"Remi",
"Margaret",
"Iris",
"Parker",
"Ximena",
"Eden",
"Ayla",
"Kylie",
"Elliana",
"Josie",
"Katherine",
"Faith",
"Alexandra",
"Eloise",
"Adalyn",
"Amaya",
"Jasmine",
"Amara",
"Daisy",
"Reese",
"Valerie",
"Brianna",
"Cecilia",
"Andrea",
"Summer",
"Valeria",
"Norah",
"Ariella",
"Esther",
"Ashley",
"Emerson",
"Aubree",
"Isabel",
"Anastasia",
"Ryleigh",
"Khloe",
"Taylor",
"Londyn",
"Lucia",
"Emersyn",
"Callie",
"Sienna",
"Blakely",
"Kehlani",
"Genevieve",
"Alina",
"Bailey",
"Juniper",
"Maeve",
"Molly",
"Harmony",
"Georgia",
"Magnolia",
"Catalina",
"Freya",
"Juliette",
"Sloane",
"June",
"Sara",
"Ada",
"Kimberly",
"River",
"Ember",
"Juliana",
"Aliyah",
"Millie",
"Brynlee",
"Teagan",
"Morgan",
"Jordyn",
"London",
"Alaina",
"Olive",
"Rosalie",
"Alyssa",
"Ariel",
"Finley",
"Arabella",
"Journee",
"Hope",
"Leila",
"Alana",
"Gemma",
"Vanessa",
"Gracie",
"Noelle",
"Marley",
"Elise",
"Presley",
"Kamila",
"Zara",
"Amy",
"Kayla",
"Payton",
"Blake",
"Ruth",
"Alani",
"Annabelle",
"Sage",
"Aspen",
"Laila",
"Lila",
"Rachel",
"Trinity",
"Daniela",
"Alexa",
"Lilly",
"Lauren",
"Elsie",
"Margot",
"Adelyn",
"Zuri",
"Brooke",
"Sawyer",
"Lilah",
"Lola",
"Selena",
"Mya",
"Sydney",
"Diana",
"Ana",
"Vera",
"Alayna",
"Nyla",
"Elaina",
"Rebecca",
"Angela",
"Kali",
"Alivia",
"Raegan",
"Rowan",
"Phoebe",
"Camilla",
"Joanna",
"Malia",
"Vivienne",
"Dakota",
"Brooklynn",
"Evangeline",
"Camille",
"Jane",
"Nicole",
"Catherine",
"Jocelyn",
"Julianna",
"Lena",
"Lucille",
"Mckenna",
"Paige",
"Adelaide",
"Charlee",
"Mariana",
"Myla",
"Mckenzie",
"Tessa",
"Miriam",
"Oakley",
"Kailani",
"Alayah",
"Amira",
"Adaline",
"Phoenix",
"Milani",
"Annie",
"Lia",
"Angelina",
"Harley",
"Cali",
"Maggie",
"Hayden",
"Leia",
"Fiona",
"Briella",
"Journey",
"Lennon",
"Saylor",
"Jayla",
"Kaia",
"Thea",
"Adriana",
"Mariah",
"Juliet",
"Oaklynn",
"Kiara",
"Alexis",
"Haven",
"Aniyah",
"Delaney",
"Gracelynn",
"Kendall",
"Winter",
"Lilith",
"Logan",
"Amiyah",
"Evie",
"Alexandria",
"Gracelyn",
"Gabriela",
"Sutton",
"Harlow",
"Madilyn",
"Makayla",
"Evelynn",
"Gia",
"Nina",
"Amina",
"Giselle",
"Brynn",
"Blair",
"Amari",
"Octavia",
"Michelle",
"Talia",
"Demi",
"Alaya",
"Kaylani",
"Izabella",
"Fatima",
"Tatum",
"Makenzie",
"Lilliana",
"Arielle",
"Palmer",
"Melissa",
"Willa",
"Samara",
"Destiny",
"Dahlia",
"Celeste",
"Ainsley",
"Rylie",
"Reign",
"Laura",
"Adelynn",
"Gabrielle",
"Remington",
"Wren",
"Brinley",
"Amora",
"Lainey",
"Collins",
"Lexi",
"Aitana",
"Alessandra",
"Kenzie",
"Raelyn",
"Elle",
"Everlee",
"Haisley",
"Hallie",
"Wynter",
"Daleyza",
"Gwendolyn",
"Paislee",
"Ariyah",
"Veronica",
"Heidi",
"Anaya",
"Cataleya",
"Kira",
"Avianna",
"Felicity",
"Aylin",
"Miracle",
"Sabrina",
"Lana",
"Ophelia",
"Elianna",
"Royalty",
"Madeleine",
"Esmeralda",
"Joy",
"Kalani",
"Esme",
"Jessica",
"Leighton",
"Ariah",
"Makenna",
"Nylah",
"Viviana",
"Camryn",
"Cassidy",
"Dream",
"Luciana",
"Maisie",
"Stevie",
"Kate",
"Lyric",
"Daniella",
"Alicia",
"Daphne",
"Frances",
"Charli",
"Raven",
"Paris",
"Nayeli",
"Serena",
"Heaven",
"Bianca",
"Helen",
"Hattie",
"Averie",
"Mabel",
"Selah",
"Allie",
"Marlee",
"Kinley",
"Regina",
"Carmen",
"Jennifer",
"Jordan",
"Alison",
"Stephanie",
"Maren",
"Kayleigh",
"Angel",
"Annalise",
"Jacqueline",
"Braelynn",
"Emory",
"Rosemary",
"Scarlet",
"Amanda",
"Danielle",
"Emelia",
"Ryan",
"Carolina",
"Astrid",
"Kensley",
"Shiloh",
"Maci",
"Francesca",
"Rory",
"Celine",
"Kamryn",
"Zariah",
"Liana",
"Poppy",
"Maliyah",
"Keira",
"Skyler",
"Noa",
"Skye",
"Nadia",
"Addilyn",
"Rosie",
"Eve",
"Sarai",
"Edith",
"Jolene",
"Maddison",
"Meadow",
"Charleigh",
"Matilda",
"Elliott",
"Madelynn",
"Holly",
"Leona",
"Azalea",
"Katie",
"Mira",
"Ari",
"Kaitlyn",
"Danna",
"Cameron",
"Kyla",
"Bristol",
"Kora",
"Armani",
"Nia",
"Malani",
"Dylan",
"Remy",
"Maia",
"Dior",
"Legacy",
"Alessia",
"Shelby",
"Maryam",
"Sylvia",
"Yaretzi",
"Lorelei",
"Madilynn",
"Abby",
"Helena",
"Jimena",
"Elisa",
"Renata",
"Amber",
"Aviana",
"Carter",
"Emmy",
"Haley",
"Alondra",
"Elaine",
"Erin",
"April",
"Emely",
"Imani",
"Kennedi",
"Lorelai",
"Hanna",
"Kelsey",
"Aurelia",
"Colette",
"Jaliyah",
"Kylee",
"Macie",
"Aisha",
"Dorothy",
"Charley",
"Kathryn",
"Adelina",
"Adley",
"Monroe",
"Sierra",
"Ailani",
"Miranda",
"Mikayla",
"Alejandra",
"Amirah",
"Jada",
"Jazlyn",
"Jenna",
"Jayleen",
"Beatrice",
"Kendra",
"Lyra",
"Nola",
"Emberly",
"Mckinley",
"Myra",
"Katalina",
"Antonella",
"Zelda",
"Alanna",
"Amaia",
"Priscilla",
"Briar",
"Kaliyah",
"Itzel",
"Oaklyn",
"Alma",
"Mallory",
"Novah",
"Amalia",
"Fernanda",
"Alia",
"Angelica",
"Elliot",
"Justice",
"Mae",
"Cecelia",
"Gloria",
"Ariya",
"Virginia",
"Cheyenne",
"Aleah",
"Jemma",
"Henley",
"Meredith",
"Leyla",
"Lennox",
"Ensley",
"Zahra",
"Reina",
"Frankie",
"Lylah",
"Nalani",
"Reyna",
"Saige",
"Ivanna",
"Aleena",
"Emerie",
"Ivory",
"Leslie",
"Alora",
"Ashlyn",
"Bethany",
"Bonnie",
"Sasha",
"Xiomara",
"Salem",
"Adrianna",
"Dayana",
"Clementine",
"Karina",
"Karsyn",
"Emmie",
"Julie",
"Julieta",
"Briana",
"Carly",
"Macy",
"Marie",
"Oaklee",
"Christina",
"Malaysia",
"Ellis",
"Irene",
"Anne",
"Anahi",
"Mara",
"Rhea",
"Davina",
"Dallas",
"Jayda",
"Mariam",
"Skyla",
"Siena",
"Elora",
"Marilyn",
"Jazmin",
"Megan",
"Rosa",
"Savanna",
"Allyson",
"Milan",
"Coraline",
"Johanna",
"Melany",
"Chelsea",
"Michaela",
"Melina",
"Angie",
"Cassandra",
"Yara",
"Kassidy",
"Liberty",
"Lilian",
"Avah",
"Anya",
"Laney",
"Navy",
"Opal",
"Amani",
"Zaylee",
"Mina",
"Sloan",
"Romina",
"Ashlynn",
"Aliza",
"Liv",
"Malaya",
"Blaire",
"Janelle",
"Kara",
"Analia",
"Hadassah",
"Hayley",
"Karla",
"Chaya",
"Cadence",
"Kyra",
"Alena",
"Ellianna",
"Katelyn",
"Kimber",
"Laurel",
"Lina",
"Capri",
"Braelyn",
"Faye",
"Kamiyah",
"Kenna",
"Louise",
"Calliope",
"Kaydence",
"Nala",
"Tiana",
"Aileen",
"Sunny",
"Zariyah",
"Milana",
"Giuliana",
"Eileen",
"Elodie",
"Rayna",
"Monica",
"Galilea",
"Journi",
"Lara",
"Marina",
"Aliana",
"Harmoni",
"Jamie",
"Holland",
"Emmalyn",
"Lauryn",
"Chanel",
"Tinsley",
"Jessie",
"Lacey",
"Elyse",
"Janiyah",
"Jolie",
"Ezra",
"Marleigh",
"Roselyn",
"Lillie",
"Louisa",
"Madisyn",
"Penny",
"Kinslee",
"Treasure",
"Zaniyah",
"Estella",
"Jaylah",
"Khaleesi",
"Alexia",
"Dulce",
"Indie",
"Maxine",
"Waverly",
"Giovanna",
"Miley",
"Saoirse",
"Estrella",
"Greta",
"Rosalia",
"Mylah",
"Teresa",
"Bridget",
"Kelly",
"Adalee",
"Aubrie",
"Lea",
"Harlee",
"Anika",
"Itzayana",
"Hana",
"Kaisley",
"Mikaela",
"Naya",
"Avalynn",
"Margo",
"Sevyn",
"Florence",
"Keilani",
"Lyanna",
"Joelle",
"Kataleya",
"Royal",
"Averi",
"Kallie",
"Winnie",
"Baylee",
"Martha",
"Pearl",
"Alaiya",
"Rayne",
"Sylvie",
"Brylee",
"Jazmine",
"Ryann",
"Kori",
"Noemi",
"Haylee",
"Julissa",
"Celia",
"Laylah",
"Rebekah",
"Rosalee",
"Aya",
"Bria",
"Adele",
"Aubrielle",
"Tiffany",
"Addyson",
"Kai",
"Bellamy",
"Leilany",
"Princess",
"Chana",
"Estelle",
"Selene",
"Sky",
"Dani",
"Thalia",
"Ellen",
"Rivka",
"Amelie",
"Andi",
"Kynlee",
"Raina",
"Vienna",
"Alianna",
"Livia",
"Madalyn",
"Mercy",
"Novalee",
"Ramona",
"Vada",
"Berkley",
"Gwen",
"Persephone",
"Milena",
"Paula",
"Clare",
"Kairi",
"Linda",
"Paulina",
"Kamilah",
"Amoura",
"Hunter",
"Isabela",
"Karen",
"Marianna",
"Sariyah",
"Theodora",
"Annika",
"Kyleigh",
"Nellie",
"Scarlette",
"Keyla",
"Kailey",
"Mavis",
"Lilianna",
"Rosalyn",
"Sariah",
"Tori",
"Yareli",
"Aubriella",
"Bexley",
"Bailee",
"Jianna",
"Keily",
"Annabella",
"Azariah",
"Denisse",
"Promise",
"August",
"Hadlee",
"Halle",
"Fallon",
"Oakleigh",
"Zaria",
"Jaylin",
"Paisleigh",
"Crystal",
"Ila",
"Aliya",
"Cynthia",
"Giana",
"Maleah",
"Rylan",
"Aniya",
"Denise",
"Emmeline",
"Scout",
"Simone",
"Noah",
"Zora",
"Meghan",
"Landry",
"Ainhoa",
"Lilyana",
"Noor",
"Belen",
"Brynleigh",
"Cleo",
"Meilani",
"Karter",
"Amaris",
"Frida",
"Iliana",
"Violeta",
"Addisyn",
"Nancy",
"Denver",
"Leanna",
"Braylee",
"Kiana",
"Wrenley",
"Barbara",
"Khalani",
"Aspyn",
"Ellison",
"Judith",
"Robin",
"Valery",
"Aila",
"Deborah",
"Cara",
"Clarissa",
"Iyla",
"Lexie",
"Anais",
"Kaylie",
"Nathalie",
"Alisson",
"Della",
"Addilynn",
"Elsa",
"Zoya",
"Layne",
"Marlowe",
"Jovie",
"Kenia",
"Samira",
"Jaylee",
"Jenesis",
"Etta",
"Shay",
"Amayah",
"Avayah",
"Egypt",
"Flora",
"Raquel",
"Whitney",
"Zola",
"Giavanna",
"Raya",
"Veda",
"Halo",
"Paloma",
"Nataly",
"Whitley",
"Dalary",
"Drew",
"Guadalupe",
"Kamari",
"Esperanza",
"Loretta",
"Malayah",
"Natasha",
"Stormi",
"Ansley",
"Carolyn",
"Corinne",
"Paola",
"Brittany",
"Emerald",
"Freyja",
"Zainab",
"Artemis",
"Jillian",
"Kimora",
"Zoie",
"Aislinn",
"Emmaline",
"Ayleen",
"Queen",
"Jaycee",
"Murphy",
"Nyomi",
"Elina",
"Hadleigh",
"Marceline",
"Marisol",
"Yasmin",
"Zendaya",
"Chandler",
"Emani",
"Jaelynn",
"Kaiya",
"Nathalia",
"Violette",
"Joyce",
"Paityn",
"Elisabeth",
"Emmalynn",
"Luella",
"Yamileth",
"Aarya",
"Luisa",
"Zhuri",
"Araceli",
"Harleigh",
"Madalynn",
"Melani",
"Laylani",
"Magdalena",
"Mazikeen",
"Belle",
"Kadence"
];
var Boys_names = [	"Liam",
"Noah",
"Oliver",
"Elijah",
"William",
"James",
"Benjamin",
"Lucas",
"Henry",
"Alexander",
"Mason",
"Michael",
"Ethan",
"Daniel",
"Jacob",
"Logan",
"Jackson",
"Levi",
"Sebastian",
"Mateo",
"Jack",
"Owen",
"Theodore",
"Aiden",
"Samuel",
"Joseph",
"John",
"David",
"Wyatt",
"Matthew",
"Luke",
"Asher",
"Carter",
"Julian",
"Grayson",
"Leo",
"Jayden",
"Gabriel",
"Isaac",
"Lincoln",
"Anthony",
"Hudson",
"Dylan",
"Ezra",
"Thomas",
"Charles",
"Christopher",
"Jaxon",
"Maverick",
"Josiah",
"Isaiah",
"Andrew",
"Elias",
"Joshua",
"Nathan",
"Caleb",
"Ryan",
"Adrian",
"Miles",
"Eli",
"Nolan",
"Christian",
"Aaron",
"Cameron",
"Ezekiel",
"Colton",
"Luca",
"Landon",
"Hunter",
"Jonathan",
"Santiago",
"Axel",
"Easton",
"Cooper",
"Jeremiah",
"Angel",
"Roman",
"Connor",
"Jameson",
"Robert",
"Greyson",
"Jordan",
"Ian",
"Carson",
"Jaxson",
"Leonardo",
"Nicholas",
"Dominic",
"Austin",
"Everett",
"Brooks",
"Xavier",
"Kai",
"Jose",
"Parker",
"Adam",
"Jace",
"Wesley",
"Kayden",
"Silas",
"Bennett",
"Declan",
"Waylon",
"Weston",
"Evan",
"Emmett",
"Micah",
"Ryder",
"Beau",
"Damian",
"Brayden",
"Gael",
"Rowan",
"Harrison",
"Bryson",
"Sawyer",
"Amir",
"Kingston",
"Jason",
"Giovanni",
"Vincent",
"Ayden",
"Chase",
"Myles",
"Diego",
"Nathaniel",
"Legend",
"Jonah",
"River",
"Tyler",
"Cole",
"Braxton",
"George",
"Milo",
"Zachary",
"Ashton",
"Luis",
"Jasper",
"Kaiden",
"Adriel",
"Gavin",
"Bentley",
"Calvin",
"Zion",
"Juan",
"Maxwell",
"Max",
"Ryker",
"Carlos",
"Emmanuel",
"Jayce",
"Lorenzo",
"Ivan",
"Jude",
"August",
"Kevin",
"Malachi",
"Elliott",
"Rhett",
"Archer",
"Karter",
"Arthur",
"Luka",
"Elliot",
"Thiago",
"Brandon",
"Camden",
"Justin",
"Jesus",
"Maddox",
"King",
"Theo",
"Enzo",
"Matteo",
"Emiliano",
"Dean",
"Hayden",
"Finn",
"Brody",
"Antonio",
"Abel",
"Alex",
"Tristan",
"Graham",
"Zayden",
"Judah",
"Xander",
"Miguel",
"Atlas",
"Messiah",
"Barrett",
"Tucker",
"Timothy",
"Alan",
"Edward",
"Leon",
"Dawson",
"Eric",
"Ace",
"Victor",
"Abraham",
"Nicolas",
"Jesse",
"Charlie",
"Patrick",
"Walker",
"Joel",
"Richard",
"Beckett",
"Blake",
"Alejandro",
"Avery",
"Grant",
"Peter",
"Oscar",
"Matias",
"Amari",
"Lukas",
"Andres",
"Arlo",
"Colt",
"Adonis",
"Kyrie",
"Steven",
"Felix",
"Preston",
"Marcus",
"Holden",
"Emilio",
"Remington",
"Jeremy",
"Kaleb",
"Brantley",
"Bryce",
"Mark",
"Knox",
"Israel",
"Phoenix",
"Kobe",
"Nash",
"Griffin",
"Caden",
"Kenneth",
"Kyler",
"Hayes",
"Jax",
"Rafael",
"Beckham",
"Javier",
"Maximus",
"Simon",
"Paul",
"Omar",
"Kaden",
"Kash",
"Lane",
"Bryan",
"Riley",
"Zane",
"Louis",
"Aidan",
"Paxton",
"Maximiliano",
"Karson",
"Cash",
"Cayden",
"Emerson",
"Tobias",
"Ronan",
"Brian",
"Dallas",
"Bradley",
"Jorge",
"Walter",
"Josue",
"Khalil",
"Damien",
"Jett",
"Kairo",
"Zander",
"Andre",
"Cohen",
"Crew",
"Hendrix",
"Colin",
"Chance",
"Malakai",
"Clayton",
"Daxton",
"Malcolm",
"Lennox",
"Martin",
"Jaden",
"Kayson",
"Bodhi",
"Francisco",
"Cody",
"Erick",
"Kameron",
"Atticus",
"Dante",
"Jensen",
"Cruz",
"Finley",
"Brady",
"Joaquin",
"Anderson",
"Gunner",
"Muhammad",
"Zayn",
"Derek",
"Raymond",
"Kyle",
"Angelo",
"Reid",
"Spencer",
"Nico",
"Jaylen",
"Jake",
"Prince",
"Manuel",
"Ali",
"Gideon",
"Stephen",
"Ellis",
"Orion",
"Rylan",
"Eduardo",
"Mario",
"Rory",
"Cristian",
"Odin",
"Tanner",
"Julius",
"Callum",
"Sean",
"Kane",
"Ricardo",
"Travis",
"Wade",
"Warren",
"Fernando",
"Titus",
"Leonel",
"Edwin",
"Cairo",
"Corbin",
"Dakota",
"Ismael",
"Colson",
"Killian",
"Major",
"Tate",
"Gianni",
"Elian",
"Remy",
"Lawson",
"Niko",
"Nasir",
"Kade",
"Armani",
"Ezequiel",
"Marshall",
"Hector",
"Desmond",
"Kason",
"Garrett",
"Jared",
"Cyrus",
"Russell",
"Cesar",
"Tyson",
"Malik",
"Donovan",
"Jaxton",
"Cade",
"Romeo",
"Nehemiah",
"Sergio",
"Iker",
"Caiden",
"Jay",
"Pablo",
"Devin",
"Jeffrey",
"Otto",
"Kamari",
"Ronin",
"Johnny",
"Clark",
"Ari",
"Marco",
"Edgar",
"Bowen",
"Jaiden",
"Grady",
"Zayne",
"Sullivan",
"Jayceon",
"Sterling",
"Andy",
"Conor",
"Raiden",
"Royal",
"Royce",
"Solomon",
"Trevor",
"Winston",
"Emanuel",
"Finnegan",
"Pedro",
"Luciano",
"Harvey",
"Franklin",
"Noel",
"Troy",
"Princeton",
"Johnathan",
"Erik",
"Fabian",
"Oakley",
"Rhys",
"Porter",
"Hugo",
"Frank",
"Damon",
"Kendrick",
"Mathias",
"Milan",
"Peyton",
"Wilder",
"Callan",
"Gregory",
"Seth",
"Matthias",
"Briggs",
"Ibrahim",
"Roberto",
"Conner",
"Quinn",
"Kashton",
"Sage",
"Santino",
"Kolton",
"Alijah",
"Dominick",
"Zyaire",
"Apollo",
"Kylo",
"Reed",
"Philip",
"Kian",
"Shawn",
"Kaison",
"Leonidas",
"Ayaan",
"Lucca",
"Memphis",
"Ford",
"Baylor",
"Kyson",
"Uriel",
"Allen",
"Collin",
"Ruben",
"Archie",
"Dalton",
"Esteban",
"Adan",
"Forrest",
"Alonzo",
"Isaias",
"Leland",
"Jase",
"Dax",
"Kasen",
"Gage",
"Kamden",
"Marcos",
"Jamison",
"Francis",
"Hank",
"Alexis",
"Tripp",
"Frederick",
"Jonas",
"Stetson",
"Cassius",
"Izaiah",
"Eden",
"Maximilian",
"Rocco",
"Tatum",
"Keegan",
"Aziel",
"Moses",
"Bruce",
"Lewis",
"Braylen",
"Omari",
"Mack",
"Augustus",
"Enrique",
"Armando",
"Pierce",
"Moises",
"Asa",
"Shane",
"Emmitt",
"Soren",
"Dorian",
"Keanu",
"Zaiden",
"Raphael",
"Deacon",
"Abdiel",
"Kieran",
"Phillip",
"Ryland",
"Zachariah",
"Casey",
"Zaire",
"Albert",
"Baker",
"Corey",
"Kylan",
"Denver",
"Gunnar",
"Jayson",
"Drew",
"Callen",
"Jasiah",
"Drake",
"Kannon",
"Braylon",
"Sonny",
"Bo",
"Moshe",
"Huxley",
"Quentin",
"Rowen",
"Santana",
"Cannon",
"Kenzo",
"Wells",
"Julio",
"Nikolai",
"Conrad",
"Jalen",
"Makai",
"Benson",
"Derrick",
"Gerardo",
"Davis",
"Abram",
"Mohamed",
"Ronald",
"Raul",
"Arjun",
"Dexter",
"Kaysen",
"Jaime",
"Scott",
"Lawrence",
"Ariel",
"Skyler",
"Danny",
"Roland",
"Chandler",
"Yusuf",
"Samson",
"Case",
"Zain",
"Roy",
"Rodrigo",
"Sutton",
"Boone",
"Saint",
"Saul",
"Jaziel",
"Hezekiah",
"Alec",
"Arturo",
"Jamari",
"Jaxtyn",
"Julien",
"Koa",
"Reece",
"Landen",
"Koda",
"Darius",
"Sylas",
"Ares",
"Kyree",
"Boston",
"Keith",
"Taylor",
"Johan",
"Edison",
"Sincere",
"Watson",
"Jerry",
"Nikolas",
"Quincy",
"Shepherd",
"Brycen",
"Marvin",
"Dariel",
"Axton",
"Donald",
"Bodie",
"Finnley",
"Onyx",
"Rayan",
"Raylan",
"Brixton",
"Colby",
"Shiloh",
"Valentino",
"Layton",
"Trenton",
"Landyn",
"Alessandro",
"Ahmad",
"Gustavo",
"Ledger",
"Ridge",
"Ander",
"Ahmed",
"Kingsley",
"Issac",
"Mauricio",
"Tony",
"Leonard",
"Mohammed",
"Uriah",
"Duke",
"Kareem",
"Lucian",
"Marcelo",
"Aarav",
"Leandro",
"Reign",
"Clay",
"Kohen",
"Dennis",
"Samir",
"Ermias",
"Otis",
"Emir",
"Nixon",
"Ty",
"Sam",
"Fletcher",
"Wilson",
"Dustin",
"Hamza",
"Bryant",
"Flynn",
"Lionel",
"Mohammad",
"Cason",
"Jamir",
"Aden",
"Dakari",
"Justice",
"Dillon",
"Layne",
"Zaid",
"Alden",
"Nelson",
"Devon",
"Titan",
"Chris",
"Khari",
"Zeke",
"Noe",
"Alberto",
"Roger",
"Brock",
"Rex",
"Quinton",
"Alvin",
"Cullen",
"Azariah",
"Harlan",
"Kellan",
"Lennon",
"Marcel",
"Keaton",
"Morgan",
"Ricky",
"Trey",
"Karsyn",
"Langston",
"Miller",
"Chaim",
"Salvador",
"Amias",
"Tadeo",
"Curtis",
"Lachlan",
"Amos",
"Anakin",
"Krew",
"Tomas",
"Jefferson",
"Yosef",
"Bruno",
"Korbin",
"Augustine",
"Cayson",
"Mathew",
"Vihaan",
"Jamie",
"Clyde",
"Brendan",
"Jagger",
"Carmelo",
"Harry",
"Nathanael",
"Mitchell",
"Darren",
"Ray",
"Jedidiah",
"Jimmy",
"Lochlan",
"Bellamy",
"Eddie",
"Rayden",
"Reese",
"Stanley",
"Joe",
"Houston",
"Douglas",
"Vincenzo",
"Casen",
"Emery",
"Joziah",
"Leighton",
"Marcellus",
"Atreus",
"Aron",
"Hugh",
"Musa",
"Tommy",
"Alfredo",
"Junior",
"Neil",
"Westley",
"Banks",
"Eliel",
"Melvin",
"Maximo",
"Briar",
"Colten",
"Lance",
"Nova",
"Trace",
"Axl",
"Ramon",
"Vicente",
"Brennan",
"Caspian",
"Remi",
"Deandre",
"Legacy",
"Lee",
"Valentin",
"Ben",
"Louie",
"Westin",
"Wayne",
"Benicio",
"Grey",
"Zayd",
"Gatlin",
"Mekhi",
"Orlando",
"Bjorn",
"Harley",
"Alonso",
"Rio",
"Aldo",
"Byron",
"Eliseo",
"Ernesto",
"Talon",
"Thaddeus",
"Brecken",
"Kace",
"Kellen",
"Enoch",
"Kiaan",
"Lian",
"Creed",
"Rohan",
"Callahan",
"Jaxxon",
"Ocean",
"Crosby",
"Dash",
"Gary",
"Mylo",
"Ira",
"Magnus",
"Salem",
"Abdullah",
"Kye",
"Tru",
"Forest",
"Jon",
"Misael",
"Madden",
"Braden",
"Carl",
"Hassan",
"Emory",
"Kristian",
"Alaric",
"Ambrose",
"Dario",
"Allan",
"Bode",
"Boden",
"Juelz",
"Kristopher",
"Genesis",
"Idris",
"Ameer",
"Anders",
"Darian",
"Kase",
"Aryan",
"Dane",
"Guillermo",
"Elisha",
"Jakobe",
"Thatcher",
"Eugene",
"Ishaan",
"Larry",
"Wesson",
"Yehuda",
"Alvaro",
"Bobby",
"Bronson",
"Dilan",
"Kole",
"Kyro",
"Tristen",
"Blaze",
"Brayan",
"Jadiel",
"Kamryn",
"Demetrius",
"Maurice",
"Arian",
"Kabir",
"Rocky",
"Rudy",
"Randy",
"Rodney",
"Yousef",
"Felipe",
"Robin",
"Aydin",
"Dior",
"Kaiser",
"Van",
"Brodie",
"London",
"Eithan",
"Stefan",
"Ulises",
"Camilo",
"Branson",
"Jakari",
"Judson",
"Yahir",
"Zavier",
"Damari",
"Jakob",
"Jaxx",
"Bentlee",
"Cain",
"Niklaus",
"Rey",
"Zahir",
"Aries",
"Blaine",
"Kyng",
"Castiel",
"Henrik",
"Joey",
"Khalid",
"Bear",
"Graysen",
"Jair",
"Kylen",
"Darwin",
"Alfred",
"Ayan",
"Kenji",
"Zakai",
"Avi",
"Cory",
"Fisher",
"Jacoby",
"Osiris",
"Harlem",
"Jamal",
"Santos",
"Wallace",
"Brett",
"Fox",
"Leif",
"Maison",
"Reuben",
"Adler",
"Zev",
"Calum",
"Kelvin",
"Zechariah",
"Bridger",
"Mccoy",
"Seven",
"Shepard",
"Azrael",
"Leroy",
"Terry",
"Harold",
"Mac",
"Mordechai",
"Ahmir",
"Cal",
"Franco",
"Trent",
"Blaise",
"Coen",
"Dominik",
"Marley",
"Davion",
"Jeremias",
"Riggs",
"Jones",
"Will",
"Damir",
"Dangelo",
"Canaan",
"Dion",
"Jabari",
"Landry",
"Salvatore",
"Kody",
"Hakeem",
"Truett",
"Gerald",
"Lyric",
"Gordon",
"Jovanni",
"Kamdyn",
"Alistair",
"Cillian",
"Foster",
"Terrance",
"Murphy",
"Zyair",
"Cedric",
"Rome",
"Abner",
"Colter",
"Dayton",
"Jad",
"Xzavier",
"Rene",
"Vance",
"Duncan",
"Frankie",
"Bishop",
"Davian",
"Everest",
"Heath",
"Jaxen",
"Marlon",
"Maxton",
"Reginald",
"Harris",
"Jericho",
"Keenan",
"Korbyn",
"Wes",
"Eliezer",
"Jeffery",
"Kalel",
"Kylian",
"Turner",
"Willie",
"Rogelio",
"Ephraim"
];